[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking", "json", "serde_json"] }
serde_json = "1.0"
wasm-bindgen-futures = "0.4.33"
yew = "0.19.3"
yew-chart = "0.5.0"
humantime = "2.1.0"